# this is configuration for using NNI built-in tuners
authorName: default
experimentName: bert_adl
trialConcurrency: 1
maxExecDuration: 24h
maxTrialNum: 36
nniManagerIp: 10.20.41.120
trainingServicePlatform: adl
searchSpacePath: search_space.json
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner
  builtinTunerName: TPE
  classArgs:
   optimize_mode: maximize
trial:
  command: python3 /root/examples/bert-adaptdl/run_classifier_nni.py
  codeDir: .
  gpuNum: 1
  image: registry.petuum.com/dev/nni:tmp-test-bert
  imagePullSecrets:
    - name: stagingsecret
  checkpoint:
    storageClass: aws-efs
    storageSize: 1Gi
