authorName: default
experimentName: lr_adl
trialConcurrency: 1
maxExecDuration: 1h
maxTrialNum: 10
nniManagerIp: 10.20.100.181
trainingServicePlatform: adl
searchSpacePath: search_space.json
#choice: true, false
useAnnotation: false
tuner:
  #choice: TPE, Random, Anneal, Evolution, BatchTuner, MetisTuner, GPTuner
  #SMAC (SMAC should be installed through nnictl)
  builtinTunerName: TPE
  classArgs:
    #choice: maximize, minimize
    optimize_mode: minimize
trial:
  command: python3 /root/apps/nni_linear_regression/main.py
  codeDir: .
  gpuNum: 0
  image: registry.petuum.com/dev/adaptdl-submit@sha256:e3b01e8ae9f54e8b1298c9ef9679cfaaee77162a34a7e3fa39b17098e2685223
  imagePullSecrets:
    - name: stagingsecrets
  checkpoint:
    storageClass: dfs
    storageSize: 1Gi
  nfs:
    server: 172.20.188.236
    path: /export
    containerMountPath: /nfs
