authorName: default
experimentName: cifar_adl
trialConcurrency: 1
maxExecDuration: 3h
maxTrialNum: 10
nniManagerIp: 10.20.41.69
trainingServicePlatform: adl
searchSpacePath: search_space_demo.json
useAnnotation: false
tuner:
  builtinTunerName: TPE
  classArgs:
    optimize_mode: minimize
trial:
  command: python3 /root/apps/pytorch-cifar/main_nni.py
  codeDir: .
  gpuNum: 1
  image: registry.petuum.com/dev/nni:tmp-nni-cifar
  imagePullSecrets:
    - name: stagingsecret
  checkpoint:
    storageClass: dfs
    storageSize: 1Gi